### PR TITLE
WebAssembly (Emscripten) port

### PR DESCRIPTION
**Pull request by RicoRodriges**
First of all I want to thank every contributors. You reimplemented one of my favorite game! I see how much has been done. It is amazing!

This pull request allows you to compile project to wasm code. Compiled once this code can work on any devices with different operation systems. You need web browser only.

The port is playable but with some audio limitations. I explained all in `README.md` file.

Changelog:
- WebAssembly port.
- Added and improved `CMakeLists.txt` files. Now you can compile cmake project as Windows (without terrible `.sln` configuration) or Emscripten application. But I don't check Linux and Android.
- Changed `README.md` file.

### CODE REVIEW

**Comment by pjasicek** [comment]
Wow - thank you for your work, it's really impressive :-)

If this changeset does not break native windows/linux builds, I can merge it right away.

Once I build it (or can you upload somewhere the emscripten compiled files?) I will upload it to my personal website - [www.jasicek.net](www.jasicek.net)

**Comment by RicoRodriges** [comment]
- AppVeyor built project for Windows from `.sln`.
- Travis built project for Linux from cmake file but failed because SDL library does not exist (I think it's ok).
- I checked cmake for Emscripten and Windows.
- I think you have no idea how build it for Android :)

So I think it can be merged if you have no objections.

After merge I can create release in my forked repository with 3 compiled binary files.

**Comment by RicoRodriges** [comment]
Maybe later I will investigate how use CI systems to build Emscripten projects.

**Comment by pjasicek** [comment]
Alright, merged, once again thank you very much for the contribution :-)

Android build - we had it running I think 3 years ago but we did not attempt to revive that since then :laughing:

**Comment by RicoRodriges** [comment]
You can take built version here for your personal website if you don't want to compile it yourself https://github.com/RicoRodriges/OpenClaw/releases

**Comment by pjasicek** [comment]
[https://jasicek.net/openclawjs/openclaw.html](https://jasicek.net/openclawjs/openclaw.html)

I love it !

By the way is there a way to make the window bigger ? I think as it is now it is 640*480

**Comment by RicoRodriges** [comment]
Change `config.xml` and recompile is the best way or now.
But `openclaw.data` isn't encrypted. You can edit it in binary editor. (Notepad++ or something like this should be fine).

**Comment by jstasiak** [comment]
> https://jasicek.net/openclawjs/openclaw.html

@pjasicek Just a heads up, the TLS certificate is expired.

**Pull request merged**
